<a href="https://colab.research.google.com/github/yabbou/python-data-science/blob/main/hw_4_(numpy).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

1. (10 Points) Write a Python/NumPy code block that finds the distinct/**unique** common items between these two
arrays:

```
a = np.array([1, 2, 3, 2, 3, 4, 3, 4, 5, 6])
b = np.array([7, 2, 10, 2, 7, 4, 9, 4, 9, 8])
```
Your output should contain only the distinct overlapping values. For example, if a 2 is found in both array a and array b,
your output should contain only one 2 even if array a contains more than one 2 within it.

In [ ]:
import numpy as np

a = np.array([1, 2, 3, 2, 3, 4, 3, 4, 5, 6])
b = np.array([7, 2, 10, 2, 7, 4, 9, 4, 9, 8])
unique = np.union1d(a,b)
print(unique)

[ 1  2  3  4  5  6  7  8  9 10]


2. (10 Points) Create the following 5x3 array using knowledge you have of Python’s / NumPy’s sequencing functionality
so that you do not need to explicitly key in every integer value.

|   |    |    |
|---|----|--- |
| 1 | 6  | 11 |
| 2 | 7  | 12 |
| 3 | 8  | 13 |
| 4 | 9  | 14 |
| 5 | 10 | 15 |

In [ ]:
two_dim = np.arange(1,16).reshape(3,5)
two_dim = two_dim.T
print(two_dim)

[[ 1  6 11]
 [ 2  7 12]
 [ 3  8 13]
 [ 4  9 14]
 [ 5 10 15]]


3. (10 Points) The process of transforming a multidimensional array into a unidimensional array is referred to as
“flattening”. Transform the 5x3 array shown above in Problem 2 into a unidimensional array such that the sequence of
values contained within the array is as follows: 
```1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15```

In [ ]:
flat = arr.reshape(1,15) #arr.flat[:]
flat.sort()
print(flat)

[[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]]


4. (15 Points) Transform the 2-D array shown in Problem 2 into a 3 dimensional array such that the first column
becomes the first dimension of the 3-D array, the second column becomes the second dimension of the 3-D array, and
the third column becomes the third dimension of the 3-D array.

In [ ]:
print('Two dimenstional:\n\n',two_dim,'\n')

three_dim = arr.T.reshape((three_dim.shape[0], three_dim.shape[1], 1)) #np.asarray(arr.T).reshape(3,5,1)
print('Three dimenstional:\n\n',three_dim)

Two dimenstional:

 [[ 1  6 11]
 [ 2  7 12]
 [ 3  8 13]
 [ 4  9 14]
 [ 5 10 15]] 

Three dimenstional:

 [[[ 1]
  [ 2]
  [ 3]
  [ 4]
  [ 5]]

 [[ 6]
  [ 7]
  [ 8]
  [ 9]
  [10]]

 [[11]
  [12]
  [13]
  [14]
  [15]]]


5. (15 Points) Transform the 3-D array you created in Problem 4 back to the 2-dimensional format shown in Problem

In [ ]:
two_dim_again = np.asarray(three_dim.T).reshape(5,3)
print(two_dim_again)

[[ 1  6 11]
 [ 2  7 12]
 [ 3  8 13]
 [ 4  9 14]
 [ 5 10 15]]


#Part 2

6. (10 Points) You are given the following two arrays:
```
a = np.array([12, 5, 7, 15, 3, 1, 8])
b = np.array([14, 6, 3, 11, 19, 12, 5])
```
Write a Python/Numpy code block that removes from array a any items that are also present in array b

In [ ]:
import numpy as np

a = np.array([12, 5, 7, 15, 3, 1, 8])
b = np.array([14, 6, 3, 11, 19, 12, 5])

a=np.setdiff1d(a,b)
print(a)

[ 1  7  8 15]


7. (30 Points) For this problem you will load a small data set to your online GitHub repository and then read it into a
NumPy 2D array. You will then use the content that NumPy array to answer a series of analytical questions.
The original source of the data set contains an overview of its content
[here](https://data.cityofnewyork.us/Environment/Water-Consumption-In-The-New-York-City/ia2d-e54m). Scroll down to the bottom of that page to access the interactive data viewer that includes the column headings for the
data. Once you are comfortable in your understanding of the various data attributes, get started on the assignment as
follows:

1) Load the provided cityData.csv file to your online Github Repository.

2) Then, from within your Jupyter Notebook, read the data set from your Github repository and load it into a Pandas
dataframe.

In [ ]:
import numpy as np
import pandas as pd

# supress scientific notation
np.set_printoptions(suppress = True)
# read the data file from GitHub and convert to a NumPy ndarray object
nyc_water_df = pd.read_csv('https://raw.githubusercontent.com/yabbou/python-data-science/main/hw_3/City_Data.csv')
nyc_water = nyc_water_df.to_numpy()

# verify you have an ndarray object
type(nyc_water)

numpy.ndarray

Using the `nyc_water` array you’ve created, answer the following questions using NumPy’s slicing, methods, and functions:
* What is the maximum yearly NYC **consumption of water** (in millions of gallons per day)?
* How many **calendar years** are represented within this data set? NumPy's shape command is one way to find out.
* What is the **mean** and the **standard deviation** of the per capita daily water consumption?
* What is the **increase/decrease in population** from year to year? Use NumPy's `diff` function to create an array of
differences; save that to a variable called `pop_diff`; then print that variable to the screen.

Student attempt for question seven:
--

First: To understand the numpy data, the column headings could be retrieved from the data when as a pandas `DataFrame`:

In [ ]:
nyc_water_df.columns

Index(['Year', 'New York City Population',
       'NYC Consumption(Million gallons per day)',
       'Per Capita(Gallons per person per day)'],
      dtype='object')

So the NYC water consumption index is 2.

In [ ]:
WATER_CONSUMPTION_INDEX = 2
annual_water_consumption = nyc_water[:, WATER_CONSUMPTION_INDEX]
max_water = int(max(annual_water_consumption) * 1_000_000)

print(f'Max: {max_water:,} gallons per day')

Max: 1,512,000,000 gallons per day


Second: To find out the number of years of recorded NYC water consunmption data is stored in the array, we could use the array's *shape*-- the default row-column count. The number of rows (the 0th index in the `shape` array's returned result) will be the number of years of recorded data.

In [ ]:
print(nyc_water.shape[0],'years')

39 years


Thrid: To find the mean number of gallons per capita and the standard deviation from that mean, we will use the array's fourth column (index 3), as seen from part 1 above.

In [ ]:
gallons_per_captia = nyc_water[:, 3]
mean_water = gallons_per_captia.mean()
print(f'Mean: {mean_water:,.2f} gallons per capita, per person per day')

std_water = gallons_per_captia.std()
print(f'Stdv: {std_water:,.2f} gallons')

Mean: 160.31 gallons per capita, per person per day
Stdv: 31.52 gallons


Fourth: The NYC population data is stored in the 2nd column (index 1). 

In [96]:
population = nyc_water[:, 1]
population_diff = np.diff(population)

print('Population differences\n',population_diff)

Population differences
 [-30461.   17602.   19864.   72119.   53290.   39540.   45192.   23230.
  11243.   -9544.   -8525.   38851.   54443.   77222.   64292.   62582.
  64772.   75631.   84816.   89401.   60618.   16685.5  16685.5  16685.5
  16685.5  16685.5  16685.5  16685.5  16685.5  16685.5  16685.5 108965.
  77081.   61281.   49530.   44512.   21171.   85025. ]
